### ISSUE TITLE
Formal v12 compatibility

### ISSUE THREAD

**Issue by weepingminotaur** [mrkwnzl/disable-mouse-wheel-sliders-foundryvtt#11]
Just a quick request for formal v12 compatibility. I'm not on v12 yet so I don't know if it works without issue on v12.

**Comment by BladeFireLight** [comment]
I modified Data/modules/disable-mouse-wheel-sliders/module.json in my instance and changed  "maximum": "12"
it seems to work fine.

**Comment by mrkwnzl** [comment]
Sorry for the late reply. My computer is in repair right now, but I should get it back next week. I’ll have a V12 update then.

**Comment by mrkwnzl** [comment]
Update 2.1.0 is ready for V12. Thank you for your patience.
