### ISSUE TITLE
Is there a reason this is locked to 0.8 versions of Foundry?

### ISSUE THREAD

**Issue by linxcat** [mrkwnzl/disable-mouse-wheel-sliders-foundryvtt#2]
Trying to install this in 0.7.10 (which is still necessary for many systems such as LANCER) gives a version error because of the minimum viable version in your module.json. Have you tried this in older version and found that it doesn't work?

**Comment by mrkwnzl** [comment]
Hi! Yes, I needed to make a change that rendered it dysfunctional for Foundry 0.7.

You can use this manifest link to install v1.1.0: https://raw.githubusercontent.com/mrkwnzl/disable-mouse-wheel-sliders-foundryvtt/v1.1.0/module.json

**Comment by linxcat** [comment]
Thank you
