### ISSUE TITLE
"Disable Inputs" Has No Effect in Firefox

### ISSUE THREAD

**Issue by patrickburk1988** [mrkwnzl/disable-mouse-wheel-sliders-foundryvtt#3]
Disabling sliders works fine in Firefox, but disabling numeric inputs does not. It looks like the `disableInputNumbers` listener doesn't actually get registered on the page init.

The `mousewheel` event is deprecated anyway, I think. This could probably be easily fixed by changing line 44 of "disable-mouse-wheel-sliders.js" to the following:
```javascript
document.addEventListener("wheel", disableInputNumbers);
```

**Comment by mrkwnzl** [comment]
Hi!

> Disabling sliders works fine in Firefox, but disabling numeric inputs does not. It looks like the disableInputNumbers listener doesn't actually get registered on the page init.

I can’t replicate this, but because in Firefox I can’t change numeric input fields with the mouse wheel at all ever, regardless of module settings. Even with the module disabled, I can’t use the mouse wheel to change numeric input fields. I’ll have to investigate. But in the meantime: What version of Firefox are you using? What’s your OS? What’s your version of Foundry? And what’s your version of the Module (just to be completely sure)?

> The `mousewheel` event is deprecated anyway, I think. This could probably be easily fixed by changing line 44 of "disable-mouse-wheel-sliders.js" to the following:
> ```javascript
> document.addEventListener("wheel", disableInputNumbers);
> ```

Thanks, I missed that. `window.addEventListener("wheel", disableInputNumbers);` should be the way to go.

**Comment by patrickburk1988** [comment]
Very interesting! I've always been able to change the numeric input fields in Firefox with the mouse wheel.

I'm running Firefox 89.0.1 (64-bit) on Windows 10. Forge is running Foundry 0.8.7. "Disable Inputs" hasn't ever worked for me, though, and I think I started using Forge around 0.7.6. Current module version is 1.1.3.

Thanks for taking a look at this!

**Comment by mrkwnzl** [comment]
Thanks for the details. I’m on Firefox 89.0.1 as well, but on macOS 11.2. Maybe there’s a bug in the macOS version that prevents me from using the mouse wheel. But that makes it kind of hard for me to test whether it works.

But I found that this is actually a very old Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=53579

`r.blur()` simply doesn’t work on Firefox. As a workaround, I found that adding `return false;` might do the trick, but I can’t test that. Would you be comfortable with changing the code on your end and adding `return false;` after line 12 of disable-mouse-wheel-sliders.js and test if that works?

If that alone doesn’t work, could you try also changing line 44 (or 45 if you’ve added a line) to `window.addEventListener("wheel", disableInputNumbers);` and see if that helps?

**Comment by patrickburk1988** [comment]
`return false;` alone doesn't seem to work, but changing line 44/45 to `window.addEventListener("wheel", disableInputNumbers);` does.

**Comment by mrkwnzl** [comment]
So, just to be completely clear, if you add `return false;` *and* change line 44/45 to `window.addEventListener("wheel", disableInputNumbers);`, it’s working as expected for you, meaning that it prevents numerical input fields to be changed with the mouse wheel?

**Comment by patrickburk1988** [comment]
Yes, adding/changing those two lines seems to prevent changing numerical input fields with the mouse wheel.

**Comment by mrkwnzl** [comment]
Fixed in v1.1.4.

Thank you very much for ringing it to my attention and confirming the fix!
