### ISSUE TITLE
Feature Request: keybinding to scroll

### ISSUE THREAD

**Issue by diannetea** [mrkwnzl/disable-mouse-wheel-sliders-foundryvtt#4]
A settable keybind for scrolling while hovering over the sliders/inputs would be really fancy.  (e.g. holding ctrl while hovering over a bar would allow it to scroll)

oh also, sidenote, I tried to DM you on Discord but you can only contact either friends or people you share servers with _if_ their settings allow it, so either you're not in the Foundry Discord or your privacy settings are disabled for DMs from server members.

**Comment by mrkwnzl** [comment]
Hey! That’s a good idea. I’ll see if I can implement that.

As for the Discord DMs: That’s strange. Other people were always able to message me. If have the setting for that enabled both on my account and on the Foundry server. Maybe there was a hiccup with the Discord servers. Would you mind trying again later, just to see if my settings are correct?

**Comment by mrkwnzl** [comment]
v1.2.0 implements this for ctrl/cmd and alt/option. Let me know if it’s working how you imagined.

**Comment by diannetea** [comment]
It's perfect, thank you!

**Comment by mrkwnzl** [comment]
Thanks for testing! I’ll close this for now, but feel free to open it in case anything goes wring with this.
