### ISSUE TITLE
Feature Request: Use requiresReload instead of forcing location.reload() on settings change

### ISSUE THREAD

**Issue by esheyw** [mrkwnzl/disable-mouse-wheel-sliders-foundryvtt#7]
Forcing a reload on any setting change is *very* jarring and not best practice, you can just set `requiresReload: true` in the setting registration and it'll prompt to reload.

**Comment by mrkwnzl** [comment]
When I created the module, that was indeed the best practice. I hadn’t noticed that `requiresReload` has been introduced. Thank you for bringing that to my attention.

Done in v1.2.7.

**Comment by esheyw** [comment]
Yea, I phrased that poorly, I was very annoyed for like a 5 minute span there as I was *not* prepared for that reload and had more than I could easily remember open 😅 thanks for the update 😄

**Comment by mrkwnzl** [comment]
It’s all good. I created the module in Foundry v0.7 and I was surprised that forcing the reload on change was the best we could do. I hadn’t checked whether a better way was introduced after that as nothing else I did needed a reload.

I’m sorry for the inconvenience it caused.
